version: 1.0.{build}
configuration: Release
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: JcXfR3krX0yQrxVt0wVeEWk4S1fyK5+P/DMyrF6QriNbe4VckM6PscHwrSUWPy2v
  skip_symbols: true